/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * InlineResponse20017Numbers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse20017Numbers {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("order_reference")
  private String orderReference = null;

  @SerializedName("country_code")
  private String countryCode = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("city_name")
  private String cityName = null;

  @SerializedName("area_code")
  private String areaCode = null;

  @SerializedName("did_group_id")
  private Integer didGroupId = null;

  @SerializedName("did_number")
  private String didNumber = null;

  @SerializedName("expiration_date")
  private LocalDate expirationDate = null;

  @SerializedName("status")
  private String status = null;

  public InlineResponse20017Numbers id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20017Numbers orderReference(String orderReference) {
    this.orderReference = orderReference;
    return this;
  }

   /**
   * Get orderReference
   * @return orderReference
  **/
  @ApiModelProperty(value = "")
  public String getOrderReference() {
    return orderReference;
  }

  public void setOrderReference(String orderReference) {
    this.orderReference = orderReference;
  }

  public InlineResponse20017Numbers countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public InlineResponse20017Numbers country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public InlineResponse20017Numbers cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public InlineResponse20017Numbers areaCode(String areaCode) {
    this.areaCode = areaCode;
    return this;
  }

   /**
   * Get areaCode
   * @return areaCode
  **/
  @ApiModelProperty(value = "")
  public String getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  public InlineResponse20017Numbers didGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
    return this;
  }

   /**
   * Get didGroupId
   * @return didGroupId
  **/
  @ApiModelProperty(value = "")
  public Integer getDidGroupId() {
    return didGroupId;
  }

  public void setDidGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
  }

  public InlineResponse20017Numbers didNumber(String didNumber) {
    this.didNumber = didNumber;
    return this;
  }

   /**
   * Get didNumber
   * @return didNumber
  **/
  @ApiModelProperty(value = "")
  public String getDidNumber() {
    return didNumber;
  }

  public void setDidNumber(String didNumber) {
    this.didNumber = didNumber;
  }

  public InlineResponse20017Numbers expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }

  public InlineResponse20017Numbers status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017Numbers inlineResponse20017Numbers = (InlineResponse20017Numbers) o;
    return Objects.equals(this.id, inlineResponse20017Numbers.id) &&
        Objects.equals(this.orderReference, inlineResponse20017Numbers.orderReference) &&
        Objects.equals(this.countryCode, inlineResponse20017Numbers.countryCode) &&
        Objects.equals(this.country, inlineResponse20017Numbers.country) &&
        Objects.equals(this.cityName, inlineResponse20017Numbers.cityName) &&
        Objects.equals(this.areaCode, inlineResponse20017Numbers.areaCode) &&
        Objects.equals(this.didGroupId, inlineResponse20017Numbers.didGroupId) &&
        Objects.equals(this.didNumber, inlineResponse20017Numbers.didNumber) &&
        Objects.equals(this.expirationDate, inlineResponse20017Numbers.expirationDate) &&
        Objects.equals(this.status, inlineResponse20017Numbers.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderReference, countryCode, country, cityName, areaCode, didGroupId, didNumber, expirationDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017Numbers {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderReference: ").append(toIndentedString(orderReference)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("    didGroupId: ").append(toIndentedString(didGroupId)).append("\n");
    sb.append("    didNumber: ").append(toIndentedString(didNumber)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

