/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2003Created;
import java.io.IOException;

/**
 * InlineResponse2004Inbox
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse2004Inbox {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("did_id")
  private Integer didId = null;

  @SerializedName("filename")
  private String filename = null;

  @SerializedName("filesize")
  private String filesize = null;

  @SerializedName("number")
  private String number = null;

  @SerializedName("sender")
  private String sender = null;

  @SerializedName("total_pages")
  private Integer totalPages = null;

  @SerializedName("created_at")
  private InlineResponse2003Created createdAt = null;

  @SerializedName("preview_file")
  private String previewFile = null;

  @SerializedName("file_url")
  private String fileUrl = null;

  public InlineResponse2004Inbox id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse2004Inbox didId(Integer didId) {
    this.didId = didId;
    return this;
  }

   /**
   * Get didId
   * @return didId
  **/
  @ApiModelProperty(value = "")
  public Integer getDidId() {
    return didId;
  }

  public void setDidId(Integer didId) {
    this.didId = didId;
  }

  public InlineResponse2004Inbox filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public InlineResponse2004Inbox filesize(String filesize) {
    this.filesize = filesize;
    return this;
  }

   /**
   * Get filesize
   * @return filesize
  **/
  @ApiModelProperty(value = "")
  public String getFilesize() {
    return filesize;
  }

  public void setFilesize(String filesize) {
    this.filesize = filesize;
  }

  public InlineResponse2004Inbox number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public InlineResponse2004Inbox sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @ApiModelProperty(value = "")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }

  public InlineResponse2004Inbox totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public InlineResponse2004Inbox createdAt(InlineResponse2003Created createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2003Created getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(InlineResponse2003Created createdAt) {
    this.createdAt = createdAt;
  }

  public InlineResponse2004Inbox previewFile(String previewFile) {
    this.previewFile = previewFile;
    return this;
  }

   /**
   * Get previewFile
   * @return previewFile
  **/
  @ApiModelProperty(value = "")
  public String getPreviewFile() {
    return previewFile;
  }

  public void setPreviewFile(String previewFile) {
    this.previewFile = previewFile;
  }

  public InlineResponse2004Inbox fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * Get fileUrl
   * @return fileUrl
  **/
  @ApiModelProperty(value = "")
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004Inbox inlineResponse2004Inbox = (InlineResponse2004Inbox) o;
    return Objects.equals(this.id, inlineResponse2004Inbox.id) &&
        Objects.equals(this.didId, inlineResponse2004Inbox.didId) &&
        Objects.equals(this.filename, inlineResponse2004Inbox.filename) &&
        Objects.equals(this.filesize, inlineResponse2004Inbox.filesize) &&
        Objects.equals(this.number, inlineResponse2004Inbox.number) &&
        Objects.equals(this.sender, inlineResponse2004Inbox.sender) &&
        Objects.equals(this.totalPages, inlineResponse2004Inbox.totalPages) &&
        Objects.equals(this.createdAt, inlineResponse2004Inbox.createdAt) &&
        Objects.equals(this.previewFile, inlineResponse2004Inbox.previewFile) &&
        Objects.equals(this.fileUrl, inlineResponse2004Inbox.fileUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, didId, filename, filesize, number, sender, totalPages, createdAt, previewFile, fileUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004Inbox {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    didId: ").append(toIndentedString(didId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    filesize: ").append(toIndentedString(filesize)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    previewFile: ").append(toIndentedString(previewFile)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

