/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20012Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse20012Data {
  @SerializedName("country")
  private String country = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("a2_code")
  private String a2Code = null;

  @SerializedName("dial_code")
  private Integer dialCode = null;

  public InlineResponse20012Data country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public InlineResponse20012Data slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @ApiModelProperty(value = "")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public InlineResponse20012Data a2Code(String a2Code) {
    this.a2Code = a2Code;
    return this;
  }

   /**
   * Get a2Code
   * @return a2Code
  **/
  @ApiModelProperty(value = "")
  public String getA2Code() {
    return a2Code;
  }

  public void setA2Code(String a2Code) {
    this.a2Code = a2Code;
  }

  public InlineResponse20012Data dialCode(Integer dialCode) {
    this.dialCode = dialCode;
    return this;
  }

   /**
   * Get dialCode
   * @return dialCode
  **/
  @ApiModelProperty(value = "")
  public Integer getDialCode() {
    return dialCode;
  }

  public void setDialCode(Integer dialCode) {
    this.dialCode = dialCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012Data inlineResponse20012Data = (InlineResponse20012Data) o;
    return Objects.equals(this.country, inlineResponse20012Data.country) &&
        Objects.equals(this.slug, inlineResponse20012Data.slug) &&
        Objects.equals(this.a2Code, inlineResponse20012Data.a2Code) &&
        Objects.equals(this.dialCode, inlineResponse20012Data.dialCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, slug, a2Code, dialCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012Data {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    a2Code: ").append(toIndentedString(a2Code)).append("\n");
    sb.append("    dialCode: ").append(toIndentedString(dialCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

