/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2008Files;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2008
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse2008 {
  @SerializedName("status")
  private String status = null;

  @SerializedName("files")
  private List<InlineResponse2008Files> files = null;

  public InlineResponse2008 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the API request
   * @return status
  **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse2008 files(List<InlineResponse2008Files> files) {
    this.files = files;
    return this;
  }

  public InlineResponse2008 addFilesItem(InlineResponse2008Files filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<InlineResponse2008Files>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * File data
   * @return files
  **/
  @ApiModelProperty(value = "File data")
  public List<InlineResponse2008Files> getFiles() {
    return files;
  }

  public void setFiles(List<InlineResponse2008Files> files) {
    this.files = files;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inlineResponse2008 = (InlineResponse2008) o;
    return Objects.equals(this.status, inlineResponse2008.status) &&
        Objects.equals(this.files, inlineResponse2008.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, files);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

