/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse200 {
  @SerializedName("status")
  private String status = null;

  @SerializedName("fax_job_id")
  private Integer faxJobId = null;

  @SerializedName("user_cash_balance")
  private BigDecimal userCashBalance = null;

  @SerializedName("cost")
  private BigDecimal cost = null;

  public InlineResponse200 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the API request
   * @return status
  **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse200 faxJobId(Integer faxJobId) {
    this.faxJobId = faxJobId;
    return this;
  }

   /**
   * The id of the fax job. It is used to check the status of the fax job.
   * @return faxJobId
  **/
  @ApiModelProperty(value = "The id of the fax job. It is used to check the status of the fax job.")
  public Integer getFaxJobId() {
    return faxJobId;
  }

  public void setFaxJobId(Integer faxJobId) {
    this.faxJobId = faxJobId;
  }

  public InlineResponse200 userCashBalance(BigDecimal userCashBalance) {
    this.userCashBalance = userCashBalance;
    return this;
  }

   /**
   * The remaining cash balance
   * @return userCashBalance
  **/
  @ApiModelProperty(value = "The remaining cash balance")
  public BigDecimal getUserCashBalance() {
    return userCashBalance;
  }

  public void setUserCashBalance(BigDecimal userCashBalance) {
    this.userCashBalance = userCashBalance;
  }

  public InlineResponse200 cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * The cost of sending fax
   * @return cost
  **/
  @ApiModelProperty(value = "The cost of sending fax")
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.status, inlineResponse200.status) &&
        Objects.equals(this.faxJobId, inlineResponse200.faxJobId) &&
        Objects.equals(this.userCashBalance, inlineResponse200.userCashBalance) &&
        Objects.equals(this.cost, inlineResponse200.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, faxJobId, userCashBalance, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    faxJobId: ").append(toIndentedString(faxJobId)).append("\n");
    sb.append("    userCashBalance: ").append(toIndentedString(userCashBalance)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

