/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20016Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse20016Data {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("did_id")
  private Integer didId = null;

  @SerializedName("did_group_id")
  private Integer didGroupId = null;

  @SerializedName("country_code")
  private String countryCode = null;

  @SerializedName("city_name")
  private String cityName = null;

  @SerializedName("area_code")
  private String areaCode = null;

  @SerializedName("number")
  private String number = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("trunk_id")
  private Integer trunkId = null;

  public InlineResponse20016Data id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20016Data didId(Integer didId) {
    this.didId = didId;
    return this;
  }

   /**
   * Get didId
   * @return didId
  **/
  @ApiModelProperty(value = "")
  public Integer getDidId() {
    return didId;
  }

  public void setDidId(Integer didId) {
    this.didId = didId;
  }

  public InlineResponse20016Data didGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
    return this;
  }

   /**
   * Get didGroupId
   * @return didGroupId
  **/
  @ApiModelProperty(value = "")
  public Integer getDidGroupId() {
    return didGroupId;
  }

  public void setDidGroupId(Integer didGroupId) {
    this.didGroupId = didGroupId;
  }

  public InlineResponse20016Data countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public InlineResponse20016Data cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public InlineResponse20016Data areaCode(String areaCode) {
    this.areaCode = areaCode;
    return this;
  }

   /**
   * Get areaCode
   * @return areaCode
  **/
  @ApiModelProperty(value = "")
  public String getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  public InlineResponse20016Data number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public InlineResponse20016Data type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InlineResponse20016Data trunkId(Integer trunkId) {
    this.trunkId = trunkId;
    return this;
  }

   /**
   * Get trunkId
   * @return trunkId
  **/
  @ApiModelProperty(value = "")
  public Integer getTrunkId() {
    return trunkId;
  }

  public void setTrunkId(Integer trunkId) {
    this.trunkId = trunkId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016Data inlineResponse20016Data = (InlineResponse20016Data) o;
    return Objects.equals(this.id, inlineResponse20016Data.id) &&
        Objects.equals(this.didId, inlineResponse20016Data.didId) &&
        Objects.equals(this.didGroupId, inlineResponse20016Data.didGroupId) &&
        Objects.equals(this.countryCode, inlineResponse20016Data.countryCode) &&
        Objects.equals(this.cityName, inlineResponse20016Data.cityName) &&
        Objects.equals(this.areaCode, inlineResponse20016Data.areaCode) &&
        Objects.equals(this.number, inlineResponse20016Data.number) &&
        Objects.equals(this.type, inlineResponse20016Data.type) &&
        Objects.equals(this.trunkId, inlineResponse20016Data.trunkId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, didId, didGroupId, countryCode, cityName, areaCode, number, type, trunkId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016Data {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    didId: ").append(toIndentedString(didId)).append("\n");
    sb.append("    didGroupId: ").append(toIndentedString(didGroupId)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    areaCode: ").append(toIndentedString(areaCode)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    trunkId: ").append(toIndentedString(trunkId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

