/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20014Areacodes;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20014
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse20014 {
  @SerializedName("status")
  private String status = null;

  @SerializedName("areacodes")
  private List<InlineResponse20014Areacodes> areacodes = null;

  public InlineResponse20014 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the API request
   * @return status
  **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse20014 areacodes(List<InlineResponse20014Areacodes> areacodes) {
    this.areacodes = areacodes;
    return this;
  }

  public InlineResponse20014 addAreacodesItem(InlineResponse20014Areacodes areacodesItem) {
    if (this.areacodes == null) {
      this.areacodes = new ArrayList<InlineResponse20014Areacodes>();
    }
    this.areacodes.add(areacodesItem);
    return this;
  }

   /**
   * Area Codes data
   * @return areacodes
  **/
  @ApiModelProperty(value = "Area Codes data")
  public List<InlineResponse20014Areacodes> getAreacodes() {
    return areacodes;
  }

  public void setAreacodes(List<InlineResponse20014Areacodes> areacodes) {
    this.areacodes = areacodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20014 inlineResponse20014 = (InlineResponse20014) o;
    return Objects.equals(this.status, inlineResponse20014.status) &&
        Objects.equals(this.areacodes, inlineResponse20014.areacodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, areacodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20014 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    areacodes: ").append(toIndentedString(areacodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

