/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20013States;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20013
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T11:58:53.587+08:00")
public class InlineResponse20013 {
  @SerializedName("status")
  private String status = null;

  @SerializedName("states")
  private List<InlineResponse20013States> states = null;

  public InlineResponse20013 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the API request
   * @return status
  **/
  @ApiModelProperty(value = "The status of the API request")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse20013 states(List<InlineResponse20013States> states) {
    this.states = states;
    return this;
  }

  public InlineResponse20013 addStatesItem(InlineResponse20013States statesItem) {
    if (this.states == null) {
      this.states = new ArrayList<InlineResponse20013States>();
    }
    this.states.add(statesItem);
    return this;
  }

   /**
   * States data
   * @return states
  **/
  @ApiModelProperty(value = "States data")
  public List<InlineResponse20013States> getStates() {
    return states;
  }

  public void setStates(List<InlineResponse20013States> states) {
    this.states = states;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013 inlineResponse20013 = (InlineResponse20013) o;
    return Objects.equals(this.status, inlineResponse20013.status) &&
        Objects.equals(this.states, inlineResponse20013.states);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, states);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    states: ").append(toIndentedString(states)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

