/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20012;
import io.swagger.client.model.InlineResponse20013;
import io.swagger.client.model.InlineResponse20014;
import io.swagger.client.model.InlineResponse20015;
import io.swagger.client.model.InlineResponse20016;
import io.swagger.client.model.InlineResponse20017;
import io.swagger.client.model.InlineResponse2004;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FaxReceivingApi
 */
@Ignore
public class FaxReceivingApiTest {

    private final FaxReceivingApi api = new FaxReceivingApi();

    
    /**
     * This API gets a list of countries with its area code
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void areaCodesCountryCodeStateIdGetTest() throws ApiException {
        Integer COUNTRY_CODE = null;
        Integer STATE_ID = null;
        String apiKey = null;
        InlineResponse20014 response = api.areaCodesCountryCodeStateIdGet(COUNTRY_CODE, STATE_ID, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of DID groups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void countriesCountryCodeDidGroupsGetTest() throws ApiException {
        Integer COUNTRY_CODE = null;
        Integer areaCode = null;
        String apiKey = null;
        Integer didGroupIds = null;
        Integer stateId = null;
        Integer cityNamePattern = null;
        InlineResponse20015 response = api.countriesCountryCodeDidGroupsGet(COUNTRY_CODE, areaCode, apiKey, didGroupIds, stateId, cityNamePattern);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of countries available in the Fax.to coverage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void countriesGetTest() throws ApiException {
        String apiKey = null;
        InlineResponse20012 response = api.countriesGet(apiKey);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of incoming faxes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void incomingFaxesGetTest() throws ApiException {
        String apiKey = null;
        String limit = null;
        String page = null;
        InlineResponse2004 response = api.incomingFaxesGet(apiKey, limit, page);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of incoming faxes for a specific recipient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void incomingFaxesRecipientGetTest() throws ApiException {
        Integer recipient = null;
        String apiKey = null;
        String limit = null;
        String page = null;
        InlineResponse2004 response = api.incomingFaxesRecipientGet(recipient, apiKey, limit, page);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of numbers to get the current configuration of one or multiple number
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void numbersGetTest() throws ApiException {
        String apiKey = null;
        String limit = null;
        String page = null;
        InlineResponse20017 response = api.numbersGet(apiKey, limit, page);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of provisioned numbers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void provisionNumbersGetTest() throws ApiException {
        Integer didGroupId = null;
        String apiKey = null;
        InlineResponse20016 response = api.provisionNumbersGet(didGroupId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API gets a list of states of a given country available in the Fax.to coverage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statesCountryCodeGetTest() throws ApiException {
        Integer COUNTRY_CODE = null;
        String apiKey = null;
        InlineResponse20013 response = api.statesCountryCodeGet(COUNTRY_CODE, apiKey);

        // TODO: test validations
    }
    
}
