/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse20010;
import io.swagger.client.model.InlineResponse20011;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse2008;
import io.swagger.client.model.InlineResponse2009;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FaxSendingApi
 */
@Ignore
public class FaxSendingApiTest {

    private final FaxSendingApi api = new FaxSendingApi();

    
    /**
     * This API is for computing the cost of the fax to be sent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void faxDocumentIdCostsGetTest() throws ApiException {
        Integer documentId = null;
        String apiKey = null;
        String faxNumber = null;
        InlineResponse2001 response = api.faxDocumentIdCostsGet(documentId, apiKey, faxNumber);

        // TODO: test validations
    }
    
    /**
     * This API gets the history of a fax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void faxHistoryGetTest() throws ApiException {
        String apiKey = null;
        String limit = null;
        String page = null;
        InlineResponse2003 response = api.faxHistoryGet(apiKey, limit, page);

        // TODO: test validations
    }
    
    /**
     * This API gets the status of a fax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void faxJobIdStatusGetTest() throws ApiException {
        Integer faxJobId = null;
        String apiKey = null;
        InlineResponse2002 response = api.faxJobIdStatusGet(faxJobId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API is for sending a new fax in any fax numbers anywhere in the world
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void faxPostTest() throws ApiException {
         faxNumber = null;
         documentId = null;
        String apiKey = null;
        InlineResponse200 response = api.faxPost(faxNumber, documentId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API is used for cleaning a document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fileCleanGetTest() throws ApiException {
        Integer documentId = null;
        String apiKey = null;
        InlineResponse2009 response = api.fileCleanGet(documentId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API generates a preview of a document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fileGeneratePreviewGetTest() throws ApiException {
        Integer documentId = null;
        String apiKey = null;
        InlineResponse20010 response = api.fileGeneratePreviewGet(documentId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API deletes a document
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filesDocumentIDDeleteTest() throws ApiException {
        Integer documentId = null;
        String apiKey = null;
        InlineResponse20011 response = api.filesDocumentIDDelete(documentId, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API gets all the files of a certain user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void filesGetTest() throws ApiException {
        String apiKey = null;
        String limit = null;
        String page = null;
        InlineResponse2008 response = api.filesGet(apiKey, limit, page);

        // TODO: test validations
    }
    
}
