/*
 * Fax.to REST API client for Java
 * This is Fax.to REST API client for Java.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2005;
import io.swagger.client.model.InlineResponse2006;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserManagementApi
 */
@Ignore
public class UserManagementApiTest {

    private final UserManagementApi api = new UserManagementApi();

    
    /**
     * This API creates a subuser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subUserPostTest() throws ApiException {
         email = null;
         password = null;
        String apiKey = null;
        InlineResponse2006 response = api.subUserPost(email, password, apiKey);

        // TODO: test validations
    }
    
    /**
     * This API is used for logging in on an existing user account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userLoginPostTest() throws ApiException {
         email = null;
         password = null;
        InlineResponse2005 response = api.userLoginPost(email, password);

        // TODO: test validations
    }
    
    /**
     * This API registers a new user account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userPostTest() throws ApiException {
         email = null;
         password = null;
        InlineResponse2005 response = api.userPost(email, password);

        // TODO: test validations
    }
    
}
